Name = input("What is your name : ")
Occupation = input("What is your occupation? : ")
Thing = input("What is your favorite thing to do? : ")
Skill = input("What is your best skill? : ")
Food = input("What is your favorite food? : ")
Desert = input("What is your favorite Desert? : ")
Blood_Group = input("What is your Blood Group? : ")
Animal = input("What is your favorite Animal? : ")
Show = input("What is your favorite TV/WEB Show/Series? : ")
Dream = input("What you want to do before you die? : ")

print("Greetings! I'm "+Name)
print("I'm a "+Occupation)
print("I like "+Thing)
print("I'm too skilled in "+Skill)
print(Food+" is my favorite food which I can't live without.")
print(Desert+" is my favorite desert helps me to calm my mind.")
print("My blood group is "+Blood_Group)
print(Animal+" is my favorite animal that I want to keep it as a pet one day.")
print(Show+" is my Favorite one.")
print("I can't allow myself to leave this world "+Dream)
